### PR TITLE
Add RC/RC Lightning status.

### PR DESCRIPTION
**Pull request by vincentmr**
The release/release compatibility workflows are run [here](https://github.com/PennyLaneAI/pennylane-lightning/actions/workflows/compat-check-release-release.yml) but the results are not reported in the test matrix. This PR adds a column to the freeze matrix and reports the tests status.

### CODE REVIEW

**Review by mlxd — COMMENTED** [review]
Note that Catalyst is only RC/RC/RC here now, so that should be moved in the table to match Lightning Rc/RC (hard to see where to comment)

**Comment by vincentmr** [comment]
> Note that Catalyst is only RC/RC/RC here now, so that should be moved in the table to match Lightning Rc/RC (hard to see where to comment)

Will do.

**Review by AmintorDusko — APPROVED** [review]
Very good now! Thank you for that!
Also, thank you for previously anticipating the necessity of this workflow.

**Review by mudit2812 — APPROVED** [review]

**Comment by vincentmr** [comment]
@mudit2812 I cannot merge on `plugin-test-matrix`, could you please do it?

**Comment by vincentmr** [comment]
> Did we need this to be an extra column? Is latest/rc a useful datapoint for Lightning and Catalyst?

Being unsure whether to keep it or not, I erred on the side of caution and kept latest/rc. Would a single `rc/rc` column be clearer?

**Pull request merged**
