### PR TITLE
raise PL deprecations as errors

### PR DESCRIPTION
**Pull request by timmysilv**
as title says. `pytest --help` shows that it processes `-W` options before processing any `filterwarnings` config options, so this should do it.

### CODE REVIEW

**Comment by timmysilv** [comment]
many plugins use deprecated code. failures:
- [honeywell](https://github.com/PennyLaneAI/plugin-test-matrix/actions/runs/6826278138/job/18565858738?pr=57)
- [braket](https://github.com/PennyLaneAI/plugin-test-matrix/actions/runs/6826278122/job/18565858042?pr=57)
- [qisikt](https://github.com/PennyLaneAI/plugin-test-matrix/actions/runs/6826278137/job/18565857728?pr=57)
- [rigetti](https://github.com/PennyLaneAI/plugin-test-matrix/actions/runs/6826278131/job/18565859958?pr=57)

**Review by albi3ro — APPROVED** [review]
I'm good to merge this in immediately so that all the failures due to deprecations show up in the test matrix.

**Comment by trbromley** [comment]
Is this what is causing [stable/stable Braket](https://github.com/PennyLaneAI/plugin-test-matrix/actions/runs/6837270898/job/18593039179) to fail?

**Comment by timmysilv** [comment]
yes. oh boy. i'll fix it

**Comment by timmysilv** [comment]
PennyLaneAI/plugin-test-matrix#58

**Pull request merged**
