### PR TITLE
Plugin test matrix/add gpu

### PR DESCRIPTION
**Pull request by vincentmr**
This PR removes L-GPU and L-Kokkos from the plugin matrix since these repos have been archived after being integrated in the Lightning monorepo. The new compatibility workflows of the monorepo now included tests of both backends on GPU runners.

### CODE REVIEW

**Comment by timmysilv** [comment]
does this mean that if any one lightning device fails, then the badge on the matrix will turn red?

**Comment by vincentmr** [comment]
> does this mean that if any one lightning device fails, then the badge on the matrix will turn red?

Yes, clicking the link we'll know which one. I've check this out with @trbromley and @mlxd before.

**Review by timmysilv — APPROVED** [review]
that's perfect, thanks!

**Review by mudit2812 — APPROVED** [review]
@vincentmr is there any remaining work on this PR? Asking because it's still a draft PR, if not, I'll merge it immediately.

**Comment by vincentmr** [comment]
No, forgot to change the status. I think it's good to go.

**Pull request merged**
