### PR TITLE
Update quilc version

### PR DESCRIPTION
**Pull request by AlbertMitjans**
Replaced `quilc:1.22.0` by `quilc:1.23.0`.

**Note**: I avoided executing the `compile.py` file because other plugins were also updated.

### CODE REVIEW

**Comment by Jaybsoni** [comment]
@AlbertMitjans, I am not sure what you mean by avoided executing `compile.py`?

**Comment by AlbertMitjans** [comment]
> @AlbertMitjans, I am not sure what you mean by avoided executing `compile.py`?

@Jaybsoni I realised that the `compile.py` file is used to create all the workflow files. Consequently I tried updating only this file and running it to update the workflows too, but then I realised that other workflows were being modified, thus I decided to hardcode the pyquil version in the forest workflows instead.

**Comment by josh146** [comment]
> but then I realised that other workflows were being modified,

@AlbertMitjans this is fine :) was there any reason you didn't want this to happen?

Since `compile.py` is the 'source of truth', there is a chance someone else could overwrite your changes.

**Comment by AlbertMitjans** [comment]
> @AlbertMitjans this is fine :) was there any reason you didn't want this to happen?

I didn't know if we really wanted this or not. I will run `compile.py` then.

**Comment by AlbertMitjans** [comment]
@Jaybsoni Done!

**Comment by Jaybsoni** [comment]
@AlbertMitjans I see what you mean, seems there were many unrelated changes altered after executing compile.py

**Comment by Jaybsoni** [comment]
I am happy to approve since I think the Forest plugin has been updated correctly, but lets wait until after the core meeting to merge. I want to bring this up briefly.

**Review by Jaybsoni — APPROVED** [review]

**Comment by Jaybsoni** [comment]
So after reviewing the additions and digging around, I have reason to believe that the compile.py file is out of date with some changes that we would like to persist in the .yml files. Since this is independent of our main issue in this PR I have rest those .yml files and am happy to merge this.

We can open another PR (not holding up the release process) which fixes compile.py to be up to date 👍🏼

**Pull request merged**
